items.url=jdbc:sqlite:Server/src/main/resources/database/items.db
user.url=jdbc:sqlite:Server/src/main/resources/database/users.db
auction.url=jdbc:sqlite:Server/src/main/resources/database/auction.db