items.url=jdbc:sqlite:Server/src/main/resources/database/items.db
users.url=jdbc:sqlite:Server/src/main/resources/database/user.db
auction.url=jdbc:sqlite:Server/src/main/resources/database/auction.db
bid.url=jdbc:sqlite:Server/src/main/resources/database/bid.db