package app.packets;

public enum Message {
    WELCOME,
    SEND_ITEM_REQUEST,
    SEND_ITEM_RESPOND,
    BROADCAST_NEW_ITEM,
    DISCONNECT,
    NEW_AUCTION_REQUEST,
    NEW_AUCTION_RESPOND,
    NEW_AUCTION_BROADCAST,
    AUCTION_TIMEOUT,
    JOIN_AUCTION,
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    SIGNUP_REQUEST,
    SIGNUP_RESPONSE,
    NEW_PRICE_RESPOND,
    NEW_PRICE_REQUEST,
    ONLINE_USER_REQUEST,
    ONLINE_USER_RESPONSE;
}
