package app.packets;

public enum Message {
    WELCOME,
    SEND_ITEM_REQUEST,
    SEND_ITEM_RESPOND,
    BROADCAST_NEW_ITEM,
    DISCONNECT,
    NEW_AUCTION_REQUEST,
    NEW_AUCTION_RESPOND,
    NEW_AUCTION_BROADCAST,
    AUCTION_TIMEOUT,
    JOIN_AUCTION,
    CANCEL_AUCTION_REQUEST,
    CANCEL_AUCTION_RESPONSE,
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    SIGNUP_REQUEST,
    SIGNUP_RESPONSE,
    NEW_PRICE_RESPOND,
    NEW_PRICE_REQUEST,
    ONLINE_USER_REQUEST,
    ONLINE_USER_RESPONSE, 
    NEW_PRICE_BROADCAST,
    FETCH_DATA_REQUEST,
    FETCH_DATA_RESPONSE,
    WINNER_RESPOND,
    ANTI_SNIPPING_RESPOND;
}
